name: Trigger auto deployment for container-app-umzkce2uhdlom

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-umzkce2uhdlom-AutoDeployTrigger-6c514cde-ab1d-4a38-b8c0-691c16a21776.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPUMZKCE2UHDLOM_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPUMZKCE2UHDLOM_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPUMZKCE2UHDLOM_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPUMZKCE2UHDLOM_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPUMZKCE2UHDLOM_REGISTRY_PASSWORD }}
          containerAppName: container-app-umzkce2uhdlom
          resourceGroup: bestcorgiappspacead8f
          imageToBuild: default/container-app-umzkce2uhdlom:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


